### ISSUE TITLE
Sync overwrites undefined on download

### ISSUE THREAD

**Issue by KimKJDesigns** [panoply/shopify-sync#6]
Using the CLI locally, sync download overwrites all the theme files with "undefined". I'm not displayed any errors and everything looks like it's working successfully. I've double-checked my .shopifysync.json file and everything looks like it's correct.

![image](https://user-images.githubusercontent.com/4345295/82754713-1daeaf80-9dcf-11ea-8fe7-28b8612b97a4.png)

![image](https://user-images.githubusercontent.com/4345295/82754732-3d45d800-9dcf-11ea-9e9c-0977e4d9b2f9.png)

**Comment by panoply** [comment]
Ouch. I'll investigate this asap. Thanks for submitting.
