### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KimKJDesigns** [panoply/shopify-sync#7]
Switched over to pnpm, imported the repo via `pnpm add panoply/shopify-sync#master` but ran into this problem. Double checked my .shopifysync.json settings and everything is good there.

```
theme-shopify git:(master) ✗ pnpm run sync download

> @ sync /Users/.../Website/theme-shopify
> sync "download"

[17:32:42] TypeError: Cannot read property 'length' of undefined
    at /Users/.../Website/theme-shopify/node_modules/.pnpm/github.com/panoply/shopify-sync/8cbe69b34f64bc272e6eece3689274320343f11f/node_modules/shopify-sync/index.js:13:3952
    at async z (/Users/.../Website/theme-shopify/node_modules/.pnpm/github.com/panoply/shopify-sync/8cbe69b34f64bc272e6eece3689274320343f11f/node_modules/shopify-sync/index.js:13:3647)
```

Sorry dude.

**Comment by panoply** [comment]
I haven’t merged final updates to master or bumped version to NPM registry. Still a fair bit go. Your issue was auto-closed cause of hash ref in commit. Sit tight, I will most likely make this an official 1.0.0 release, ton of stuff shipping.

**Comment by panoply** [comment]
You may have luck via API as node script for time being with what is on master. Try that, let me know how you go.

**Comment by KimKJDesigns** [comment]
@panoply Ledge. I didn't end up using a node script, but after a quick update, the CLI is working. It's looking really good too. Thanks for the quick updates.
