### ISSUE TITLE
Cannot find module '../index'

### ISSUE THREAD

**Issue by possibleworlds** [panoply/shopify-sync#8]
Hey, thanks for this package, works a treat usually!

Getting below on latest release.

```bash
Cannot find module '../index'
Require stack:
- <path>/node_modules/shopify-sync/bin/sync
```

Changing to `../package/index` fixes my end.

**Comment by panoply** [comment]
Hey @possibleworlds, what package manager are you using?

**Comment by panoply** [comment]
@possibleworlds Fixed! It seems I forgot to relink the CLI package, thanks for taking the time to submit the issue, really appreciate it.

**Comment by possibleworlds** [comment]
Thanks! Just for reference was with plain old npm.

**Comment by panoply** [comment]
Just curious, As a user, is there any features you’d like to see in the first major? I’ll be shipping a fair few improvements. Would being able to minify help you? Or is there something missing that you would like to see? Do you use the CLI over the script? Any insights will be great, thanks.

**Comment by possibleworlds** [comment]
Hey, no not really actually, it ticks all the boxes for me! I am using config file with targets for dev / live, and I generally use https://github.com/sezna/nps so basically npm scripts to trigger.

My main pain point (besides Shopify generally) is localhost server setup. I use browsersync just because I am used to using it, but the config is cobbled together from other repos and manually figuring out the preview_theme_id and installing ssl feels fragile. A proxy server that does all this based on the sync config would be a nice to have, either as part of this module or as a separate package.

**Comment by panoply** [comment]
Thanks for getting back to me, I can optionally provide a way print the theme id via the CLI. I do have a complete dev environment locally that I use for developing themes that provides all this, I will see what I can do in terms of potentially combining it.

**Comment by possibleworlds** [comment]
Yeah, yours is probably one of the boilerplates I was using, that or the slater-theme. For me its the boilerplate involved that turns me off, and only having a vague understanding of whether what I am doing is correct... something that abstracts that config away so I can be lazy would be great, but I don't think its the role or responsibility of this lib. Will look at your strap again.
